services:
  - type: web
    name: qca-backend
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn qca.app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_PRICE_PRO
        sync: false
      - key: STRIPE_PRICE_ENTERPRISE
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SA95_PROMO_CODE
        value: SA95
      - key: MAX_HISTORY_TURNS
        value: 8
